#if !canImport(ObjectiveC)
import XCTest

extension BoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoxTests = [
        ("testBox", testBox),
    ]
}

extension MutableBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MutableBoxTests = [
        ("testMutableBox", testMutableBox),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BoxTests.__allTests__BoxTests),
        testCase(MutableBoxTests.__allTests__MutableBoxTests),
    ]
}
#endif
